### ISSUE TITLE
Memory usage out of control after last update

### ISSUE THREAD

**Issue by theCrius** [theCrius/project-zomboid-random-zombies-full#15]
Something else is broken, we can't join the server anymore
We are at 30gb RAM and have around 30gb free ram (total 64gbs of ram)

```
WARN : Multiplayer , 1720718174101> 479,655,166> MPStatistics.lambda$Init$6> [MPStatistics] java.management.memory.threshold.exceeded (10) free=2,919,235,584
WARN : Multiplayer , 1720718272953> 479,754,020> MPStatistics.lambda$Init$6> [MPStatistics] java.management.memory.threshold.exceeded (11) free=2,946,498,560
WARN : Multiplayer , 1720718330781> 479,811,849> MPStatistics.lambda$Init$6> [MPStatistics] java.management.memory.threshold.exceeded (12) free=2,917,138,432
WARN : Multiplayer , 1720718387762> 479,868,831> MPStatistics.lambda$Init$6> [MPStatistics] java.management.memory.threshold.exceeded (13) free=2,948,595,712

```

_Originally posted by @6-- in https://github.com/theCrius/project-zomboid-random-zombies-full/issues/14#issuecomment-2223488598_

**Comment by theCrius** [comment]
After running a server with 16GB of RAM for a couple hours I haven't detected any RAM spikes.

However I have used default settings for sandbox_var and default settings for the mod, with only this mod activated.

Seems that the issue is not generated by this mod **OR** a specific configuration is causing it. Might be something that happens with incredibly high population server.

**Comment by 6--** [comment]
Sorry for the delay, heres what we had

```
    RandomZombiesFull = {
        -- Minimum=1000 Maximum=60000 Default=7500
        Frequency = 7500,
        Enable_Day = 2,
        Enable_Night = 2,
        Enable_Special = 1,
        Special_Threshold = 2,
        -- Minimum=0 Maximum=23 Default=23
        Summer_Night_Start = 23,
        -- Minimum=0 Maximum=23 Default=6
        Summer_Night_End = 6,
        -- Minimum=0 Maximum=23 Default=22
        Autumn_Night_Start = 22,
        -- Minimum=0 Maximum=23 Default=6
        Autumn_Night_End = 6,
        -- Minimum=0 Maximum=23 Default=20
        Winter_Night_Start = 20,
        -- Minimum=0 Maximum=23 Default=6
        Winter_Night_End = 6,
        -- Minimum=0 Maximum=23 Default=22
        Spring_Night_Start = 22,
        -- Minimum=0 Maximum=23 Default=6
        Spring_Night_End = 6,
        -- Minimum=0.00 Maximum=100.00 Default=5.00
        Crawler_Day = 5.0,
        -- Minimum=0.00 Maximum=100.00 Default=65.00
        Shambler_Day = 33.0,
        -- Minimum=0.00 Maximum=100.00 Default=25.00
        FastShambler_Day = 58.0,
        -- Minimum=0.00 Maximum=100.00 Default=5.00
        Sprinter_Day = 4.0,
        -- Minimum=0.00 Maximum=100.00 Default=30.00
        Fragile_Day = 30.0,
        -- Minimum=0.00 Maximum=100.00 Default=50.00
        Normal_Day = 50.0,
        -- Minimum=0.00 Maximum=100.00 Default=20.00
        Tough_Day = 20.0,
        -- Minimum=0.00 Maximum=100.00 Default=5.00
        Smart_Day = 10.0,
        -- Minimum=0.00 Maximum=100.00 Default=5.00
        Crawler_Night = 5.0,
        -- Minimum=0.00 Maximum=100.00 Default=25.00
        Shambler_Night = 43.0,
        -- Minimum=0.00 Maximum=100.00 Default=65.00
        FastShambler_Night = 50.0,
        -- Minimum=0.00 Maximum=100.00 Default=5.00
        Sprinter_Night = 2.0,
        -- Minimum=0.00 Maximum=100.00 Default=30.00
        Fragile_Night = 30.0,
        -- Minimum=0.00 Maximum=100.00 Default=50.00
        Normal_Night = 50.0,
        -- Minimum=0.00 Maximum=100.00 Default=20.00
        Tough_Night = 20.0,
        -- Minimum=0.00 Maximum=100.00 Default=5.00
        Smart_Night = 10.0,
        -- Minimum=0.00 Maximum=100.00 Default=5.00
        Crawler_Special = 5.0,
        -- Minimum=0.00 Maximum=100.00 Default=5.00
        Shambler_Special = 5.0,
        -- Minimum=0.00 Maximum=100.00 Default=25.00
        FastShambler_Special = 25.0,
        -- Minimum=0.00 Maximum=100.00 Default=65.00
        Sprinter_Special = 65.0,
        -- Minimum=0.00 Maximum=100.00 Default=30.00
        Fragile_Special = 30.0,
        -- Minimum=0.00 Maximum=100.00 Default=50.00
        Normal_Special = 50.0,
        -- Minimum=0.00 Maximum=100.00 Default=20.00
        Tough_Special = 20.0,
        -- Minimum=0.00 Maximum=100.00 Default=5.00
        Smart_Special = 5.0,
    },
```

**Comment by theCrius** [comment]
Hey @6-- , this is just the section for this mod.

What I need to replicate is the entire sandboxvar ini file and the latest debug log to check for more details.

You can use pastebin.com or any cloud storage service that allow you to zip those files if they are very big (dropbox, google drive, one drive, etc etc).

**Comment by 6--** [comment]
Hey, sorry for the delay.

I can't get you the information at the moment.

Please take a look at https://github.com/theCrius/project-zomboid-random-zombies-full/issues/7

Also, check out the changelog [Random Zombies - Day and Night :: Change Notes](https://steamcommunity.com/sharedfiles/filedetails/changelog/2888099799).

> Update: 12 Nov, 2023 @ 7:16pm
> Reverting last update again. If someone has time to investigate, please come forward as I don't have time at the moment.

When you reverted that change, it actually fixed the issue. You might have accidentally pushed the wrong previous update.

Others are reporting the same issue we have. Here is the link: https://steamcommunity.com/sharedfiles/filedetails/?id=2888099799

**Comment by theCrius** [comment]
Thank @6--, I'll check out the revert I did back then.

I am in the middle of some work to be completed next tuesday and cannot really get distracted much. I'll check it out tonight to see if I can see some glaring issue that can be fixed but otherwise I'll do a more in depth check next tuesday.

In any case, the mod can be disabled and re-enabled without problem, i'm sure you know that already.

**Comment by theCrius** [comment]
@6-- I pushed a new update. Some experimental changes ended up in release when they shouldn't have. Probably I didn't notice I was on the wrong version when pushing the latest changes.

I started back from that update you mentioned and added back just the changes from @Burryaga as they were just validation for the settings.

I tested, having a quick run (48h) and checking for crashes or abnormal memory usage but didn't notice any. However, to be honest, I didn't notice any even when I checked previously, so I can't really be sure.

Please pull the updated version for your server if you can and test again. Let me know and post here the debuglog in case you still see problems. The more info I can get, the better I can work on this.

I can't promise to jump on it in the next few days as I did this evening but at worst I'll work on it next week, as I mentioned above.

Cheers

**Comment by 6--** [comment]
Thanks a lot!

It seems your latest update has fixed the issue.

Do you mind if we repack the mod to avoid future problems?

**Comment by theCrius** [comment]
No problem as long as you give credit @6-- 

However, I think I understood what has gone wrong. I was working on some changes some months ago and forgot to switch branch when merging the latest change from @Burryaga.

An unfortunate coincidence. There won't be more updates until b42 comes out anyway, but still, feel free to repack.
