### ISSUE TITLE
Mod overrides configured Zombie cognition

### ISSUE THREAD

**Issue by jgentil** [theCrius/project-zomboid-random-zombies-full#16]
**Describe the bug**
In sandbox options, if I set the default cognition to "Navigation" from "Basic Navigation", this mod will override that setting.  

**To Reproduce**
1. In "Zombie Lore" section of Sandbox Settings, change the "Cognition" value to "Navigate".
2. Wait a bit until day/night changes
3. Observe that the value always resets back to "Basic Navigation"

**Expected behavior**

That this setting would be used as the default "not smart" zombie cognition setting instead of a hard-coded one.

**Comment by theCrius** [comment]
This is the expected behaviour... If you use a mod that alter an aspect of the game, it will do that.
