### ISSUE TITLE
Dedi spam since last update

### ISSUE THREAD

**Issue by Grumpy35** [theCrius/project-zomboid-random-zombies-full#5]
Hello.. Since your last update my dedi continuously gets spammed with this:

LOG  : General     , 1685051448607> 5,245,297> [RZF] ===================
LOG  : General     , 1685051448607> 5,245,297> [RZF] speed      2       2
LOG  : General     , 1685051448607> 5,245,298> [RZF] cognition  2       -1
LOG  : General     , 1685051448607> 5,245,298> [RZF] memory     2       800
LOG  : General     , 1685051448608> 5,245,298> [RZF] sight      2       2
LOG  : General     , 1685051448608> 5,245,298> [RZF] hearing    2       2
LOG  : General     , 1685051448608> 5,245,298> [RZF] ===================

It's the same thing over and over again.

It is causing server instability. Players actions are slowed by at least 2-3 seconds. They're running into the 'black void' consistantly (loading issues). It seems to be disrupting the server performance. I am assuming it is your mod since the server was fine before the update. 

I had not changed any settings before or after the update. Nothing has been changed.

Any ideas? And if worse case scenerio happens would this mod be safe to remove mid game?

Thank you.

**Comment by theCrius** [comment]
Ah shoot, I forgot to remove a debug logging, Will release a fix asap
-- Claudio Vallesi

**Comment by theCrius** [comment]
Should be fixed, sorry about that. I've been having a long day

**Comment by Grumpy35** [comment]
No need to apologize. Mistakes happen. Thank you for your mod and thank you for the quick response/fix! Appreciate it.
