### ISSUE TITLE
game crashing at 6am every day.

### ISSUE THREAD

**Issue by ArdaSinecikli** [theCrius/project-zomboid-random-zombies-full#7]
**Describe the bug**
At 6am on every single day, the game crashes to desktop. When I reload into the save, I dont lose any progress (game unpauses at 5.50 am) but all the zombies around me are deleted, rougly as far as I can see. 

**To Reproduce**
1. Be playing the game at 5.50 am
2. As soon as the clock hits 6am, game freezes. "Project zomboid is not responding".
3. Click launch game, menu loads, click Continue.
4. Game loads, click when screen says "Click to start"
5. Game fully loads, time is 5.50 am, all zombies withing seeing range are deleted. 

**Expected behavior**
I expect the game to not crash at 6am. When it crashes, I expect the 

**Screenshots**
The mods file for the save is in the following link:
[mods.txt](https://github.com/theCrius/project-zomboid-random-zombies-full/files/11594621/mods.txt)
The log file is in the following link. 
[console.txt](https://github.com/theCrius/project-zomboid-random-zombies-full/files/11594608/console.txt)
I'll also paste the last few lines here: 
"WARN : Lua         , 1685403719689> LuaManager$GlobalObject.require> require("NVAPI/ctrl/instance") failed
LOG  : General     , 1685403736055> EXITDEBUG: setGameSpeed 1
LOG  : General     , 1685403736056> EXITDEBUG: setGameSpeed 3
WARN : Lua         , 1685403736056> LuaManager$GlobalObject.require> require("NVAPI/ctrl/instance") failed
LOG  : General     , 1685403737141> [RZF] Schedule detected is 	dayTime
LOG  : General     , 1685403737142> [RZF] Checking if preset 	dayTime	 is enabled
LOG  : General     , 1685403737142> [RZF] Schedule need to change from 	nightTime	 to 	dayTime
LOG  : General     , 1685403737142> [RZF] Disabling previous preset
LOG  : General     , 1685403737142> [RZF] Enabling new preset
LOG  : General     , 1685403737142> [RZF] Schedule Preset changed ---> 	dayTime"
that line is the last line of the console. 

**Specification (please complete the following information):**
- Game Version: 41.78.16
- Game mode: Solo. Highly customised sandbox mode.
- SandboxVars block for the mod:
[sandbox variables.txt](https://github.com/theCrius/project-zomboid-random-zombies-full/files/11594671/sandbox.variables.txt)
(the above text file contains text that I copied from "map_sand.bin" of the save file. I cleaned the text and rearranged to make it nicer to look at.)

**Additional context**
I have a LOT of mods installed, so it could be a mod conflict, but I couldnt make sense of the log file. It seems the game crashes when it switches to Day time zombies. This bug also didnt occur jsut once, its occured multiple times on this save. Im on day 4 or so, and its happened every single morning.

**Comment by theCrius** [comment]
Gave a quick look and it seems that there are a lot of errors coming from [NVAPI](https://steamcommunity.com/sharedfiles/filedetails/?id=2776633989) which is the mod to allow for night vision, which would make sense as being related to when night change to day (6AM being one of those times depending on the season).

I checked the logs and see that you are running from a windows host. Is it your own machine or a rented server?
Is it feasible for you to try and remove NVAPI and mods that requires it ([Like this one for example](https://steamcommunity.com/sharedfiles/filedetails/?id=2769995104)) and try to see if the crash happens again?

The logs reported by my mod are simple event logs that are not triggered by errors, they actually just report that everything have gone right when changing the distribution of zombies depending on the time of day 😕

**Comment by ArdaSinecikli** [comment]
Accidentally tapped "close issue", so im reopening. Apologies.

**Comment by ArdaSinecikli** [comment]
Enabling the NVAPI mod seems to have fixed the issue. Thanks again for your response.
