### ISSUE TITLE
Game crashed when it's reach 6am

### ISSUE THREAD

**Issue by jeffrey11th5** [theCrius/project-zomboid-random-zombies-full#8]
**Describe the bug**
I host a server to test if the mod is working and whenever the time reaches 6am, the game freeze till i have to close it manually.

**To Reproduce**
1. Startup a hosted server with this mod enabled
2. Wait till it's 6am
3. When it's right at 6am the game freezes, have to close when it say "Project Zomboid is not responding"
4. When i restart and loaded back, the time revert back to when server was started before 6am
5. Restart the server with the mod disabled will cause all the zombie to despawn

**Expected behavior**
I expect for the day to start at 6am and the zombies lore to change with it

Screenshots
Console file
[coop-console.txt](https://github.com/theCrius/project-zomboid-random-zombies-full/files/11601068/coop-console.txt)
modlist file
[default.txt](https://github.com/theCrius/project-zomboid-random-zombies-full/files/11601164/default.txt)
ignore the mod called The Darkness is Coming, it should be turned off.

**Specification (please complete the following information):**
- Game Version 41.78.16 (Steam)
- Game mode Hosted Server with heavily modded
- SandboxVars block for the mod sent in zip form
[Meow_SandboxVars.zip](https://github.com/theCrius/project-zomboid-random-zombies-full/files/11601049/Meow_SandboxVars.zip)

**Additional context**
I was hosting a heavily modded server and i added this mod in the middle of playthrough, started it up to see if there's any problem and i got this crash, tried to duplicate this issue on solo but it seem worked fine. I can't find any other conflict mod, this is the only mod that overwrites time of days and zombie lore

**Comment by jeffrey11th5** [comment]
Okay a little bit update, when i disabled the mod and rehost the server after crash, no zombies are to be found and when the time forward after 6am, nothing happened, so it have something to do with the zombies behavior

**Comment by jeffrey11th5** [comment]
I managed to replicate the issue solo and the same thing happened, here is the console log
[console.txt](https://github.com/theCrius/project-zomboid-random-zombies-full/files/11601501/console.txt)

**Comment by theCrius** [comment]
Just to add, I've tested the same, running a server hosted locally with just the mod going and it doesn't seem to crash anything for me really. That's why I'm asking you to check as well.

**Comment by theCrius** [comment]
@jeffrey11th5 I reverted the mod to the last version before this update. Please try and cleanup the world as well when testing mods because if something mess up the world generation (zombies, vehicles, loot, etc) that "fuck up" will persist.

In any case, reverting to the previous version should 100% means that if you still have the same issue, it's one of the two things I listed above and I can't do anything about it unfortunately.

**Comment by jeffrey11th5** [comment]
i will try load a game with just this mod, how do i make sure that all of the mod are disabled. I disabled some mod and i still see their sandbox option despite disabled in the mod menu

**Comment by theCrius** [comment]
You need to disable the mods from the mods menu in the main menu'. You'll see that there are mods enabled and disabled. Also, you need to be sure that the server mods' are loaded correctly. I suggest using [Mod Manager](https://steamcommunity.com/sharedfiles/filedetails/?id=2694448564) and [Server Mod Manager](https://steamcommunity.com/sharedfiles/filedetails/?id=2725216703)

**Comment by jeffrey11th5** [comment]
yea i know that alright and already have those mod managers, it's just that even when i disabled them from the main menu, i can still see their settings in sandbox option, idk if theres an issue or not

**Comment by jeffrey11th5** [comment]
Okay so i tried the new update, i spent 2 days in game with the mod along with other mods and it didn't crash at all

**Comment by theCrius** [comment]
Thanks for confirming @jeffrey11th5. I'll close this issue and do some research on what changed in the next update that would cause this issue. Cheers!
